In [1]:
p_storage_dir = "../../storage"

In [2]:
import pandas as pd
import numpy as np
from pathlib import Path

IFG_PRODUZ_STORAGE_DIR = Path(f"{p_storage_dir}/ifg_produz")

## Produção Bibliográfica

In [3]:
producao_bibliografica = pd.read_csv(IFG_PRODUZ_STORAGE_DIR / "extracted/producaobibliografica.csv", delimiter=";")

producao_bibliografica.head(n=5)

id_producao            doi_producao  natureza  ano_producao     idioma  \
0            1   10.22149/teee.v2i1.80  COMPLETO          2016     Inglês   
1            2   10.22149/teee.v2i1.89  COMPLETO          2016  Português   
2            3  10.22149/teee.v2i2.105  COMPLETO          2017  Português   
3            4    10.1155/2019/1303241  COMPLETO          2019     Inglês   
4            5   10.22149/teee.v2i2.99  COMPLETO          2017  Português   

  tipo                                    titulo_producao  \
0  NaN  Metric for Calculation of System Complexity ba...   
1  NaN  Calculation of the influence of slot geometry ...   
2  NaN  Proposal of heuristic regression method applie...   
3  NaN  Mechanism for Measuring System Complexity Appl...   
4  NaN  Analysis and monitoring of electrical groundin...   

  classificacao_do_evento meio_divulgacao  tipo_producao  id_conferencia_id  \
0                     NaN    MEIO_DIGITAL              1                  1   
1                     NaN    MEIO_DIGITAL              1                  1   
2                     NaN    MEIO_DIGITAL              1                  1   
3                     NaN    MEIO_DIGITAL              1                  1   
4                     NaN    MEIO_DIGITAL              1                  1   

   id_curriculo_id  id_revista_id  nome_pdf  
0                1              2       NaN  
1                1              2       NaN  
2                1              2       NaN  
3                1              4       NaN  
4                1              2       NaN

In [4]:
producao_bibliografica = producao_bibliografica.rename(columns={
    'id_producao': 'codigo',
    'ano_producao': 'ano',
    'titulo_producao': 'titulo',
    'id_conferencia_id': 'codigo_conferencia',
    'id_curriculo_id': 'codigo_curriculo',
    'id_revista_id': 'codigo_revista'
})

producao_bibliografica.sample(n=5)

codigo                doi_producao          natureza   ano     idioma  \
12668   12662                         NaN               NaN  2015  Português   
5749     5743  10.1016/j.fuel.2011.11.060          COMPLETO  2012     Inglês   
2136     2128                         NaN    TEXTO_INTEGRAL  2011  Português   
16711   16707                         NaN  RESUMO_EXPANDIDO  2006  Português   
13559   13558                         NaN            RESUMO  2006  Português   

                              tipo  \
12668  Capítulo de livro publicado   
5749                           NaN   
2136               LIVRO_PUBLICADO   
16711                          NaN   
13559                          NaN   

                                                  titulo  \
12668  Hydrochar as a soil conditioner in ecological ...   
5749   Simultaneous gas chromatographic analysis of t...   
2136   A Representação do Feminino na Ficção de Yvonn...   
16711  Prática pedagógica e formação discente no ensi...   
13559  Evasão universitária: uma questão do curso de ...   

      classificacao_do_evento meio_divulgacao  tipo_producao  \
12668                     NaN          VARIOS              5   
5749                      NaN    MEIO_DIGITAL              1   
2136                      NaN        IMPRESSO              4   
16711                REGIONAL    MEIO_DIGITAL              2   
13559                REGIONAL    MEIO_DIGITAL              2   

       codigo_conferencia  codigo_curriculo  codigo_revista  nome_pdf  
12668                   1              1095               1       NaN  
5749                    1               513            2695       NaN  
2136                    1               195               1       NaN  
16711                   1              1427               1       NaN  
13559                   1              1165               1       NaN

### Análise das colunas 'tipo' e 'tipo_produção'

In [5]:
producao_bibliografica['tipo'].unique()

array([nan, 'LIVRO_PUBLICADO', 'Capítulo de livro publicado',
       'LIVRO_ORGANIZADO_OU_EDICAO'], dtype=object)

A coluna 'tipo' possui dados válidos, o único tratamento que será feito é a renomeação de um valor para ficar no padrão dos outros, com letras maíusculas, sem acentos e com underline no lugar dos espaços.

In [6]:
cap_livro_irregular_indexes = producao_bibliografica[producao_bibliografica['tipo'] == 'Capítulo de livro publicado'].index

In [7]:
producao_bibliografica.loc[cap_livro_irregular_indexes, 'tipo'] = 'CAPITULO_DE_LIVRO_PUBLICADO'

In [8]:
producao_bibliografica['tipo'].unique()

array([nan, 'LIVRO_PUBLICADO', 'CAPITULO_DE_LIVRO_PUBLICADO',
       'LIVRO_ORGANIZADO_OU_EDICAO'], dtype=object)

---

In [9]:
producao_bibliografica['tipo_producao'].unique()

array([1, 3, 2, 4, 5])

A coluna 'tipo_producao' possui dados que aparentam ser chaves estrangeiras, entretanto analisando o DER não é possível encontrar nenhuma referência que possa nos dar alguma informação útil de que representam os números utilizados nessa coluna, por isso a coluna será removida do dataset.

In [10]:
producao_bibliografica = producao_bibliografica.drop(columns=['tipo_producao'])

producao_bibliografica.sample(n=5)

codigo doi_producao       natureza   ano     idioma  \
16729   16725          NaN            NaN  2019  Português   
20140   20141          NaN  NAO_INFORMADO  2007  Português   
16386   16384          NaN            NaN  2012  Português   
14809   14809          NaN       COMPLETO  2011  Português   
13777   13776          NaN         RESUMO  2009  Português   

                              tipo  \
16729  CAPITULO_DE_LIVRO_PUBLICADO   
20140              LIVRO_PUBLICADO   
16386  CAPITULO_DE_LIVRO_PUBLICADO   
14809                          NaN   
13777                          NaN   

                                                  titulo  \
16729                         Corpo e Juventude Skatista   
20140  Instrumento de Avaliação da gestão para os CEF...   
16386  Dança contemporânea e a pesquisa sobre o caval...   
14809  Avaliação do Desempenho Lumínico de Edificação...   
13777  A instância da escrita e da letra no documentá...   

      classificacao_do_evento meio_divulgacao  codigo_conferencia  \
16729                     NaN        IMPRESSO                   1   
20140                     NaN        IMPRESSO                   1   
16386                     NaN   NAO_INFORMADO                   1   
14809                     NaN    MEIO_DIGITAL                   1   
13777           INTERNACIONAL          VARIOS                   1   

       codigo_curriculo  codigo_revista  nome_pdf  
16729              1427               1       NaN  
20140              1663               1       NaN  
16386              1403               1       NaN  
14809              1274           15385       NaN  
13777              1172               1       NaN

### Tratamento das colunas com valores categóricos

In [13]:
from replacer import replace_na_repr_with_nan

In [81]:
producao_bibliografica['natureza'].unique()

array(['COMPLETO', 'RESUMO', 'TEXTO_INTEGRAL', nan, 'RESUMO_EXPANDIDO',
       'NAO_INFORMADO', 'OUTRA', 'COLETANEA', 'LIVRO', 'ANAIS', 'VERBETE',
       'CATALOGO'], dtype=object)

In [14]:
producao_bibliografica = replace_na_repr_with_nan(producao_bibliografica, 'NAO_INFORMADO', 'natureza')

In [43]:
producao_bibliografica['idioma'].unique()

array(['Inglês', 'Português', 'Bretão', 'Galego', 'Espanhol', 'Italiano',
       'Malgaxe', 'Outros', 'Francês', 'Russo', 'Abhkazian', 'Albanês',
       'Afar', 'Afrikaans', 'Maltês', 'Alemão', 'Árabe', 'Oria', 'Aimara'],
      dtype=object)

In [33]:
producao_bibliografica['classificacao_do_evento'].unique()

array([nan, 'NACIONAL', 'INTERNACIONAL', 'LOCAL', 'NAO_INFORMADO',
       'REGIONAL'], dtype=object)

In [16]:
producao_bibliografica = replace_na_repr_with_nan(producao_bibliografica, 'NAO_INFORMADO', 'classificacao_do_evento')

In [17]:
producao_bibliografica['meio_divulgacao'].unique()

array(['MEIO_DIGITAL', 'VARIOS', 'NAO_INFORMADO', 'IMPRESSO',
       'MEIO_MAGNETICO', 'OUTRO', 'FILME', 'HIPERTEXTO'], dtype=object)

In [18]:
producao_bibliografica = replace_na_repr_with_nan(producao_bibliografica, 'NAO_INFORMADO', 'meio_divulgacao')

In [43]:
if producao_bibliografica['nome_pdf'].isna().all():
    producao_bibliografica = producao_bibliografica.drop(columns='nome_pdf')

In [44]:
producao_bibliografica.sample(5)

codigo doi_producao  natureza   ano     idioma  \
19680   19678          NaN  COMPLETO  2006  Português   
17601   17600          NaN  COMPLETO  2004  Português   
5637     5631          NaN  COMPLETO  2013     Bretão   
413       413          NaN  COMPLETO  2007  Português   
4840     4829          NaN       NaN  2019  Português   

                              tipo  \
19680                          NaN   
17601                          NaN   
5637                           NaN   
413                            NaN   
4840   CAPITULO_DE_LIVRO_PUBLICADO   

                                                  titulo  \
19680  Gestão Participativa e os conflitos entre as c...   
17601  Roda Viva (1968) de Chico Buarque: a dramaturg...   
5637   A importância das abelhas nas produções agríco...   
413    PCH Mosquitão - O Controle Tecnológico do Conc...   
4840   Políticas Educacionais: O Ensino Médio no Bras...   

      classificacao_do_evento meio_divulgacao  codigo_conferencia  \
19680           INTERNACIONAL          VARIOS                   1   
17601                     NaN    MEIO_DIGITAL                   1   
5637            INTERNACIONAL    MEIO_DIGITAL                   1   
413                  NACIONAL          VARIOS                   1   
4840                      NaN          VARIOS                   1   

       codigo_curriculo  codigo_revista  
19680              1617               1  
17601              1481           11774  
5637                506               1  
413                  30               1  
4840                435               1

**Exportar**

In [45]:
export_path = Path(IFG_PRODUZ_STORAGE_DIR / "preprocessed")

if not export_path.is_dir():
    Path(export_path).mkdir()

producao_bibliografica.to_csv(export_path / "producao_bibliografica.csv", sep=";", index=False)